// @ts-check
/**
 * @fileoverview Mobile app copy, identifiers, and layout constants.
 */

import {
  DEFAULT_LENGTHS,
  PRESET_CONFIG,
  PRESET_IDENTIFIERS,
  TEXT_CONTENT,
  TOGGLE_IDENTIFIERS
} from "./shared-web/constants.js";

export { DEFAULT_LENGTHS, PRESET_CONFIG, PRESET_IDENTIFIERS, TOGGLE_IDENTIFIERS };

export const MOBILE_COPY = Object.freeze({
  APP_TITLE: TEXT_CONTENT.APP_TITLE,
  PRIMARY_DESCRIPTION: "Compose, split, copy, and share platform-sized threads from your phone.",
  INPUT_PLACEHOLDER: TEXT_CONTENT.EDITOR_PLACEHOLDER,
  CUSTOM_LENGTH_PLACEHOLDER: TEXT_CONTENT.CUSTOM_INPUT_PLACEHOLDER,
  CUSTOM_BUTTON_LABEL: TEXT_CONTENT.CUSTOM_BUTTON_DEFAULT,
  COPY_BUTTON_LABEL: TEXT_CONTENT.COPY_BUTTON_LABEL,
  SHARE_THREAD_LABEL: "Share thread",
  ATTACH_IMAGE_LABEL: "Attach image",
  REMOVE_IMAGE_LABEL: "Remove",
  CLEAR_BUTTON_LABEL: "Clear",
  BUILT_BY_LINE: "Built by Marco Polo Research Lab",
  PARAGRAPH_TOGGLE_LABEL: "Paragraphs",
  SENTENCE_TOGGLE_LABEL: "Sentences",
  ENUMERATION_TOGGLE_LABEL: "Enumerate",
  ERROR_NO_CONTENT: TEXT_CONTENT.ERROR_NO_TEXT,
  ERROR_INVALID_CUSTOM: TEXT_CONTENT.ERROR_INVALID_CUSTOM,
  ERROR_COPY_FAILED: "Unable to copy this chunk.",
  ERROR_SHARE_FAILED: "Unable to open the share sheet.",
  ERROR_IMAGE_PICK_FAILED: "Unable to attach that image.",
  ATTACHED_IMAGE_ALT: "Attached image",
  IMAGE_CHUNK_LABEL: "Image chunk",
  TIMELINE_MARKER_PENDING_TEMPLATE: "Chunk {CHUNKID} not copied",
  TIMELINE_MARKER_COPIED_TEMPLATE: "Chunk {CHUNKID} copied #{ORDER}",
  INPUT_STATS_EMPTY: TEXT_CONTENT.INPUT_STATS_EMPTY,
  INPUT_STATS_TEMPLATE: TEXT_CONTENT.INPUT_STATS_TEMPLATE,
  CHUNK_STATS_TEMPLATE: TEXT_CONTENT.CHUNK_STATS_TEMPLATE,
  IMAGE_PLAIN_TEXT_PLACEHOLDER: TEXT_CONTENT.IMAGE_PLAIN_TEXT_PLACEHOLDER
});

export const MOBILE_TEST_IDS = Object.freeze({
  SOURCE_INPUT: "source-input",
  INPUT_STATS: "input-stats",
  ERROR_MESSAGE: "error-message",
  CUSTOM_ROW: "custom-row",
  CUSTOM_LENGTH_INPUT: "custom-length-input",
  THREAD_CHUNK_LIST: "thread-chunk-list",
  THREAD_CHUNK_MARKER_PREFIX: "thread-chunk-marker",
  THREAD_CHUNK_TOP_LINE_PREFIX: "thread-chunk-top-line",
  THREAD_CHUNK_BOTTOM_LINE_PREFIX: "thread-chunk-bottom-line",
  TOGGLE_TRACK_PREFIX: "toggle-track",
  SHARE_THREAD_BUTTON: "share-thread-button",
  ATTACH_IMAGE_BUTTON: "attach-image-button",
  CLEAR_BUTTON: "clear-button",
  BUILT_BY_LINE: "built-by-line"
});

export const MOBILE_ACCESSIBILITY_LABELS = Object.freeze({
  PRESET_THREADS: PRESET_CONFIG[PRESET_IDENTIFIERS.THREADS].label,
  PRESET_BLUESKY: PRESET_CONFIG[PRESET_IDENTIFIERS.BLUESKY].label,
  PRESET_TWITTER: PRESET_CONFIG[PRESET_IDENTIFIERS.TWITTER].label,
  CUSTOM_APPLY: "Apply custom size",
  BREAK_ON_PARAGRAPHS: MOBILE_COPY.PARAGRAPH_TOGGLE_LABEL,
  BREAK_ON_SENTENCES: MOBILE_COPY.SENTENCE_TOGGLE_LABEL,
  ENUMERATE: MOBILE_COPY.ENUMERATION_TOGGLE_LABEL
});

export const LAYOUT_VALUES = Object.freeze({
  SCREEN_PADDING: 16,
  SECTION_GAP: 14,
  CONTROL_GAP: 8,
  CARD_PADDING: 12,
  CARD_RADIUS: 8,
  BUTTON_RADIUS: 6,
  BUTTON_HEIGHT: 44,
  TOGGLE_ROW_HEIGHT: 44,
  TOGGLE_TRACK_WIDTH: 58,
  TOGGLE_TRACK_HEIGHT: 32,
  TOGGLE_TRACK_PADDING: 3,
  TOGGLE_THUMB_SIZE: 26,
  INPUT_MIN_HEIGHT: 180,
  CUSTOM_INPUT_WIDTH: 96,
  IMAGE_PREVIEW_HEIGHT: 120,
  FOOTER_TOP_PADDING: 10,
  FOOTER_BOTTOM_PADDING: 18,
  TIMELINE_RAIL_WIDTH: 32,
  TIMELINE_MARKER_SIZE: 22,
  TIMELINE_LINE_WIDTH: 2,
  TIMELINE_MARKER_TOP_OFFSET: 12,
  TITLE_FONT_SIZE: 28,
  BODY_FONT_SIZE: 16,
  SMALL_FONT_SIZE: 13,
  STAT_FONT_SIZE: 12
});
